### PR TITLE
BasicGridElement early stage

### PR DESCRIPTION
**Pull request by biapar**
BasicGridElement early stage

### CODE REVIEW

**Review by nikcio — CHANGES_REQUESTED** [review]
Hi @biapar,

I've cleaned up your PR and renamed the files to match the project structure. Unfortunately, your PR doesn't function in my testing.

It's been tested with 3 content pages holding a default Grid editor with basic data like headlines, quotes, and Rich Text Editors. All of them fail.

I've tried changing the value conversion in `BasicGridModel.cs` line 42 to: `var value = ((JObject)propertyValue).ToObject<IEnumerable<IPublishedElement>>();` but the JObject returned doesn't have the correct structure to be able to deserialize into a `IEnumerable<IPublishedElement>`.

Examples of grid data can be seen here:
image
image

**Comment by nikcio** [comment]
#86

**Comment by biapar** [comment]
Could you show the code that use this draft? So I tried again.

I've tried also this method. 
I add into Umbraco a class model as:

`using Nikcio.UHeadless.Base.Properties.Commands;
using Nikcio.UHeadless.Basics.Properties.EditorsValues.BlockList.Models;
using Nikcio.UHeadless.Basics.Properties.Models;
using Nikcio.UHeadless.Core.Reflection.Factories;
using HotChocolate;
using Nikcio.UHeadless.Base.Properties.Models;
using Umbraco.Cms.Core.Strings;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Extensions;
using Umbraco.Cms.Core.Models;
using Newtonsoft.Json;


namespace UGCare.Models
{    /// <summary>
     /// Represents a rich text editor
     /// </summary>
    [GraphQLDescription("Represents a grid editor.")]
    public class GridPropertyValue : PropertyValue
    {

        [GraphQLDescription("Gets the value of the grid editor.")]
        public virtual string? Value { get; set; }


        public GridPropertyValue(CreatePropertyValue createPropertyValue) : base(createPropertyValue)
        {
            var value = createPropertyValue.Property.GetValue(createPropertyValue.Culture);
            
            var content = createPropertyValue.Content;
            if (content == null)
            {
                return;
            }

            foreach (var item in createPropertyValue.Content.Properties)
            {

            }

            string alias = createPropertyValue.Property.Alias;
            Value = createPropertyValue.Content.GetProperty(alias).GetValue().ToString();
        
        }
    }
}`

and from startup I call:
`.AddUHeadless(new()
                {
                    PropertyServicesOptions = new()
                    {
                        PropertyMapOptions = new()
                        {
                            PropertyMappings = new() {
                    propertyMap => propertyMap.AddEditorMapping<GridPropertyValue>("Umbraco.Grid")
                }
                        }
                    }
                })`

**Comment by nikcio** [comment]
@biapar Please update this PR with the code above if that's the best solution 😄

**Comment by nikcio** [comment]
Hi @biapar,

After testing this implementation and having it under serious consideration I've decided not to include this model in the package. With the new Grid Block editor implementation coming in 10.3 and the old Grid editor being deprecated soon I don't think there's a great argument to support the editor. Furthermore, your implementation of the model doesn't offer an output on the same quality level as the other editors because it doesn't offer any way of customizing the editors inside the grid and is just a raw JSON string.

Remember you can always implement the model in your own projects.

**Comment by biapar** [comment]
I think that the basic implementation like here https://github.com/nikcio/Nikcio.UHeadless/pull/90#issuecomment-1268728988 it's enough at moment.
When will be out the 10.3?

**Comment by nikcio** [comment]
https://umbraco.com/blog/umbraco-103-release-candidate/

**Pull request closed without merging**
